-- ******************** SqlDBM: Microsoft SQL Server ********************
-- *** Generated by SqlDBM: DDYDLS_IMDB, v11 by davidflemal@gmail.com ***


-- ************************************** [T_Movie]
CREATE TABLE [T_Movie]
(
 [Id_Movie] int NOT NULL IDENTITY ,
 [Name]     varchar(50) NOT NULL ,
 [Year]     int NOT NULL ,
 [TMDB_Id]  int NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([Id_Movie] ASC)
);
GO
